### ISSUE TITLE
NEED TO ADD WEBSOCKETS TO VIEW LIVE DATA

### ISSUE THREAD

**Issue by Ivan-E-Johnson** [Knobloch-Iowa/GreenHouse#48]

**Comment by Ivan-E-Johnson** [comment]
https://channels.readthedocs.io/en/latest/introduction.html#what-is-a-consumer
https://channels.readthedocs.io/en/latest/topics/sessions.html
https://channels.readthedocs.io/en/latest/topics/authentication.html

**Comment by namansharma18899** [comment]
@Ivan-E-Johnson  Can you elaborate a bit on the ticket. Like who would be the client in this socket connection ??

**Comment by Ivan-E-Johnson** [comment]
Connected to HiveMQ successfully and was able to send control signals from the frontend
